platform :ios, '8.0'
use_frameworks!

target ‘VieTaxi-Chofer’ do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'Alamofire', '~> 4.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Google/SignIn'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'PayPal-iOS-SDK'

end
